---
- name: Install/Configure java11 & apache tomcat & apache http server
  hosts: webservers     
  become: yes     
  become_method: sudo     
  remote_user: root 
  vars:
    java_package: java-11-openjdk
    tomcat_ver: 9.0.17
    ui_manager_user: manager
    ui_manager_pass: barath@123
    ui_admin_username: admin                    
    ui_admin_pass: barath@123
    apache_daemon_path: /usr/sbin/
    apache_server_root: /etc/httpd
    apache_conf_path: /etc/httpd/conf.d
    apache_vhosts_version: "2.2"
    apache_ports_configuration_items:
    - regexp: "^Listen "
      line: "Listen {{ apache_listen_port }}"
    - regexp: "^#?NameVirtualHost "
      line: "NameVirtualHost {{ apache_listen_ip }}:{{ apache_listen_port }}"
  roles:
    - java
    - tomcat
    - httpd
