---
- name: Install ElasticSearch Logstash Kibana
  hosts: elk
  become: true
  tasks:
  - name: Install Java
    yum:
       name:  java-1.8.0-openjdk-devel
       state: present
  - name: Add Elasticsearch apt key
    rpm_key:
       key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
       state: present
  - name: Adding Elasticsearch repository
    yum_repository:
       name: elasticsearch
       description: Elasticsearch YUM repo
       baseurl: https://artifacts.elastic.co/packages/7.x/yum
       state: present
  - name: Install ElasticSearch
    yum: 
      name: elasticsearch
      state: present
  - name: Updating the config file to allow outside access
    lineinfile:
      destfile: /etc/elasticsearch/elasticsearch.yml
      regexp: 'network.host:'
      line: 'network.host: 0.0.0.0'

  - name: Updating the port in config file 
    lineinfile:
      destfile: /etc/elasticsearch/elasticsearch.yml
      regexp: 'http.port:'
      line: 'http.port: 9200'
  - name: Starting Elasticsearch
    systemd:
     name: elasticsearch
     state: started
  - name: Install Kibana 
    yum:
      name: kibana
      state: present
  - name: Updating the config file to allow outside access
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.host:'
      line: 'server.host: 0.0.0.0'
  - name: Upating kibana port
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.port:'
      line: 'server.port: 5601'
  - name: Defining Elasticsearch URL
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.url:'
      line: 'elasticsearch.url: "http://localhost:9200"'
  - name: Starting Kibana
    systemd:
      name: kibana
      state: started
  - name: Install Logstash
    yum:
      name: logstash
      state: present
  - name: Starting Logstash
    systemd:
      name: logstash
      state: started
