---
  apache_daemon_path: /usr/sbin/
  apache_server_root: /etc/httpd
  apache_conf_path: /etc/httpd/conf.d
  apache_vhosts_version: "2.2"
  apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"
  - regexp: "^#?NameVirtualHost "
    line: "NameVirtualHost {{ apache_listen_ip }}:{{ apache_listen_port }}"