- name: copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: start and enable tomcat
  systemd:
    name: tomcat
    state: started
    enabled: yes

- name: start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: open tomcat port on the firewall
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes