- name: copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: start and enable tomcat
  systemd:
    name: tomcat
    state: started
    enabled: yes
